@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TAbleParser" as TAbleParser LOGIC_COLOR
participant ":FindStudentMatricNumberCommandParser" as FindStudentMatricNumberCommandParser LOGIC_COLOR
participant "fsmnc:FindStudentMatricNumberCommand" as FindStudentMatricNumberCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findStudentMatricNumber \nmatric/A0123456X")
activate LogicManager

LogicManager -> TAbleParser : parseCommand("findStudentMatricNumber \nmatric/A0123456X")
activate TAbleParser

create FindStudentMatricNumberCommandParser
TAbleParser -> FindStudentMatricNumberCommandParser
activate FindStudentMatricNumberCommandParser

FindStudentMatricNumberCommandParser --> TAbleParser
deactivate FindStudentMatricNumberCommandParser

TAbleParser -> FindStudentMatricNumberCommandParser : parse("A0123456X")
activate FindStudentMatricNumberCommandParser

create FindStudentMatricNumberCommand
FindStudentMatricNumberCommandParser -> FindStudentMatricNumberCommand
activate FindStudentMatricNumberCommand

FindStudentMatricNumberCommand --> FindStudentMatricNumberCommandParser : fsmnc
deactivate FindStudentMatricNumberCommand

FindStudentMatricNumberCommandParser --> TAbleParser : fsmnc
deactivate FindStudentMatricNumberCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindStudentMatricNumberCommandParser -[hidden]-> TAbleParser
destroy FindStudentMatricNumberCommandParser

TAbleParser --> LogicManager : fsmnc
deactivate TAbleParser

LogicManager -> FindStudentMatricNumberCommand : execute()
activate FindStudentMatricNumberCommand

FindStudentMatricNumberCommand -> Model : updateFilteredStudentList(A0123456X)
activate Model

Model --> FindStudentMatricNumberCommand
deactivate Model

create CommandResult
FindStudentMatricNumberCommand -> CommandResult
activate CommandResult

CommandResult --> FindStudentMatricNumberCommand
deactivate CommandResult

FindStudentMatricNumberCommand --> LogicManager : result
deactivate FindStudentMatricNumberCommand

[<--LogicManager
deactivate LogicManager
@enduml
